export const requests = {
    register: "/auth/register",
    login: "/auth/login",
    addTweet: "/tweet/addTweet",
    saveChat: "/chat/save",
    getChatHistory: "/chat/get",
    getPeopleList: "/chat",
    isReceiverValid: "/chat/validate",
    searchUser: "/search",
    getTweet: "/tweet/getTweet",
    addVote: "/profile/poll/vote/",
    retweet: "/tweet/retweet",
    repost : "/tweet/repost",
    addComment: "/tweet/addComment",
    likeTweet: "/tweet/likeTweet",
    postBookmarks: "/profile/addBookmark",
    getRecommendations: "/profile/recommended/users",
    getBookmark: "/profile/bookmarks",
}
